# Generated by Django 3.1.5 on 2021-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0003_parcelsmodel_treck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelsmodel',
            name='total_price',
        ),
        migrations.AddField(
            model_name='parcelsmodel',
            name='category',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='parcelsmodel',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='parcelsmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parcelsmodel',
            name='web_site',
            field=models.URLField(default=False),
        ),
    ]
