# Generated by Django 3.1.5 on 2021-09-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0007_auto_20210909_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
    ]
