# Generated by Django 3.1.5 on 2021-09-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_auto_20210909_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='parcels',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
