# Generated by Django 3.1.5 on 2021-09-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0010_auto_20210910_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='date',
            field=models.DateField(default='09.10.21'),
        ),
    ]
