# Generated by Django 3.1.5 on 2021-09-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0011_auto_20210910_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='date',
            field=models.DateField(default='21y/09m/10d'),
        ),
    ]
