# Generated by Django 3.1.5 on 2021-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0014_auto_20210915_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='status',
            field=models.CharField(choices=[['unregistered_order', 'незарегистрированный заказ'], ['during', 'в процессе'], ['sorting', 'сортировка'], ['processed', 'обработан1'], ['processed', 'обработан2'], ['processed', 'обработан3'], ['In_stock_in_KG', 'на складе в Kg1'], ['In_stock_in_KG', 'на складе в Kg2'], ['In_stock_in_KG', 'на складе в Kg3']], default='unregistered_order', max_length=50),
        ),
    ]
