# Generated by Django 3.1.5 on 2021-09-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0015_auto_20210915_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcels',
            name='status',
            field=models.CharField(choices=[('unregistered_order', 'незарегистрированный заказ'), ('during', 'в процессе'), ('sorting', 'сортировка'), ('processed1', 'обработан1'), ('processed2', 'обработан2'), ('processed3', 'обработан3'), ('In_stock_in_KG1', 'на складе в Kg1'), ('In_stock_in_KG2', 'на складе в Kg2'), ('In_stock_in_KG3', 'на складе в Kg3')], default='unregistered_order', max_length=50),
        ),
    ]
